### ISSUE TITLE
not working in jupterlab

### ISSUE THREAD

**Issue by saitej123** [arunnbaba/pandas_ui#11]
Instead of UI , I am getting this

Box(children=(Box(children=(Button(description='Add Python Code', layout=Layout(flex='0.4 1 auto', width='auto…
Output(layout=Layout(border='1px solid black'))

HBox(children=(Label(value='', layout=Layout(height='50px', width='0px')), Dropdown(description='Column :', la…
Output(layout=Layout(border='1px solid black'))
Label(value='1936758 rows * 30 Columns')
Output(layout=Layout(border='1px solid black'))
                                                     Table View 
QgridWidget(grid_options={'fullWidthRows': True, 'syncColumnCellResize': True, 'forceFitColumns': False, 'defa…
Output(layout=Layout(border='1px solid black'))
HBox(children=(Label(value='', layout=Layout(height='30px', width='200px')), Label(value='', layout=Layout(hei…
Output(layout=Layout(border='1px solid black'))
Output(layout=Layout(border='1px solid black'))
HBox(children=(Label(value='', layout=Layout(height='30px', width='200px')), Label(value='', layout=Layout(hei…
Output(layout=Layout(border='1px solid black'))
VBox(children=(Output(layout=Layout(border='1px solid black')), HBox(children=(Button(button_style='success', …
HBox(children=(Dropdown(description='Figure Type:', options=('scatter', 'box', 'violin', 'histogram', 'strip',…
Button(description='Plot', style=ButtonStyle(button_color='green'))
Tab(children=(Output(), Output(), Output(), Output()), _titles={'0': 'DataFrame', '1': 'PandasProfoling', '2':…
![1](https://user-images.githubusercontent.com/18657211/85207477-aa08af80-b346-11ea-9626-b84dcd8528c9.PNG)

**Comment by arunnbaba** [comment]
Please try in jupyter, I have tested it on jupyter and assumed it
would work on jupyterlab also. My bad. I'll edit the medium article and
GitHub also.

Thanks for letting me know.

It should work fine on jupyter.

**Comment by saitej123** [comment]
yes, is working in jupyter , I appreciate your efforts for creating this package. I have tested this with different datasets (sizes), file size >200 mb there is no smooth experience .  I request you to test this .

**Comment by saitej123** [comment]
Other suggestions:

- After file selection , differentiation of metrics based on datatype will be more intuitive  
Stats related to metrics can be based on selections 

- Plots are not visible properly..so resolution can be increased

**Comment by arunnbaba** [comment]
Really appreciate your suggestions.

Thank you
