### ISSUE TITLE
ModuleNotFoundError: No module named 'pandas_ui'

### ISSUE THREAD

**Issue by batmanscode** [arunnbaba/pandas_ui#12]
First off, awesome project! I saw this on this in a YT video and couldn't wait to try it out!

I pip installed inside a conda env (after activating) and when I tried `from pandas_ui import *` in a jupyter notebook I got the following error:

![image](https://user-images.githubusercontent.com/29989939/85800455-a322d800-b75e-11ea-93cd-a63eb5cce472.png)

I had already installed pandas, numpy and matplotlib via conda in this env. Would that be an issue?

**Comment by arunnbaba** [comment]
I need more details could you please share the commands you tried to
install the package and in the mean time try pip list inside your conda env
to check whether Pandas_ui is installed or not. Thanks.

**Comment by kusumagurram** [comment]
> First off, awesome project! I saw this on this in a YT video and couldn't wait to try it out!
> 
> I pip installed inside a conda env (after activating) and when I tried `from pandas_ui import *` in a jupyter notebook I got the following error:
> 
> ![image](https://user-images.githubusercontent.com/29989939/85800455-a322d800-b75e-11ea-93cd-a63eb5cce472.png)
> 
> I had already installed pandas, numpy and matplotlib via conda in this env. Would that be an issue?
Hi in jupyter notebook run the below line. i got the same issue. i too got same issue first it is solved by run after below code.

!pip install pandas_ui

**Comment by arunnbaba** [comment]
have you tried **"pip list"** to check whether it is properly installed.

If yes, please be sure you have enabled the extensions required.

Commands:
jupyter nbextension enable — py qgrid — sys-prefix
jupyter nbextension enable — py widgetsnbextension — sys-prefix

If those doesn't work on condas, try these to enable

jupyter nbextension enable --py --sys-prefix qgrid
jupyter nbextension enable --py --sys-prefix widgetsnbextension

**Comment by batmanscode** [comment]
> I need more details could you please share the commands you tried to install the package and in the mean time try pip list inside your conda env to check whether Pandas_ui is installed or not. Thanks.

Yes sure, these are the commands:

```
pip install pandas_ui

jupyter nbextension enable --py qgrid --sys-prefix

jupyter nbextension enable --py qgrid --sys-prefix

```

Btw I did this in anaconda prompt. I got "validating: ok" after each `jupyter nbextension` as well.

And `pip list` shows that I have pandas-ui 1.0 installed (along with pandas-profiling and bokeh and a few others that came with pandas_ui)

Edit: I'm running windows 10, maybe it's a windows issue?

**Comment by batmanscode** [comment]
Reinstalling worked!
