### ISSUE TITLE
Export code

### ISSUE THREAD

**Issue by ManuelBanza** [arunnbaba/pandas_ui#2]
Hi @arunnbaba ,

First of all thank you for this tool it looks really great!

Is it possible to export the code instead of looking to the history and copy it?

It seems that is not possible to use the pandas_ui without importing a file, I think it would be great if you could call the UI in a variable dataframe. Example: pandas_ui(df).

Because imagine if you do a lot of data wrangling them some visualizations and want to see the dataset again, you would have to go back to import the file and do everything from the beginning.

Maybe it is possible to do this things I didn´t catch it.

Cheers!

**Comment by arunnbaba** [comment]
Hi

Thanks for your kind words.

currently, the only option is to copy and paste the code. I haven't
tested it yet but I think it's possible to call the function with variable
name.

**Comment by ManuelBanza** [comment]
Hi,

I tried like this:

from pandas_ui import *

pandas_ui(df)

ValueError: Invalid file path or buffer object type: <class 'pandas.core.frame.DataFrame'>

thanks

**Comment by arunnbaba** [comment]
Let me check it out and get back to you

**Comment by arunnbaba** [comment]
Hi,
the variable is working fine for me please find the attached for further information.

Please check your file path and unicode.


![variable](https://user-images.githubusercontent.com/14852442/84974845-ace68300-b141-11ea-80c0-352680203f74.PNG)

**Comment by arunnbaba** [comment]
Please let me know if you are ok with closing the issue.

**Comment by ManuelBanza** [comment]
Thanks for helping!

That case works but I was talking about a dataframe variable. Example:

![Captura de ecrã 2020-06-18, às 08 50 22](https://user-images.githubusercontent.com/53525022/84993143-c6d39600-b140-11ea-85e6-50709ef4e492.png)

**Comment by arunnbaba** [comment]
Oh! am sorry that cases will not work since pandas_ui will read the file inside the function.
And thanks for the suggestion will include this in the next beta release.
