### ISSUE TITLE
Error displaying widget: model not found

### ISSUE THREAD

**Issue by edbarr** [arunnbaba/pandas_ui#21]
![image](https://user-images.githubusercontent.com/51648265/93028225-faa34800-f5d7-11ea-8f28-7586faf129e4.png)

I'm receiving this error: **"Error displaying widget: model not found"**  The rest of the GUI displays fine and it returns the cound for number of rows & columns, just not the table view itself.   

Does the qgrid widget need to be explicitly?   Is there a setting that needs to be enabled or altered?

**Comment by arunnbaba** [comment]
I can't see the code clearly but I am guessing you haven't passed a dataframe to the pandas_ui. also, check whether u r os and environment is compatible with the tool.

**Comment by arunnbaba** [comment]
As from the pic shared above. you haven't passed a CSV file to the tool and it accepts only the CSV hence the error.
