### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by SurendraRedd** [arunnbaba/pandas_ui#23]
### Pandas UI Display Issue

Installation commands mentioned in the readme file (_**1) jupyter nbextension enable — py qgrid — sys-prefix 2)jupyter nbextension enable — py widgetsnbextension — sys-prefix**_) are not working which inturn pandas ui is not displaying in the jupyter notebook.

**Workaround:**
jupyter nbextension install --user --py widgetsnbextension
jupyter nbextension enable --user --py widgetsnbextension

**Comment by arunnbaba** [comment]
Thanks for the workaround will include in the documenatation.
