### ISSUE TITLE
Not issue - Dropping Columns and Table View

### ISSUE THREAD

**Issue by jeejiahui** [arunnbaba/pandas_ui#25]
![image](https://user-images.githubusercontent.com/54544446/100846966-1d981680-34ba-11eb-8acd-37a5b50c14d6.png)

Hi. This isn't an issue. I love how convenient this widget is and how much it had helped me. 

This is just a suggestion not an issue :
1. Can we add a direct drop option in it. That way the flow would be smoother.
2. In the option of bulk dropping the data, could we add in a full view of the data frame in table form atleast, we can have a quick glance of the data column before dropping ? 

Thank you very much.
Best regards,
Jee

**Comment by arunnbaba** [comment]
hi Jee,

Thanks for commenting. I think by drop u mean deleting a column. let me know if my understanding is right or if you mean row deletion it's already available in the very first view itself. will include yours and other's recommendations in the next release.
