### ISSUE TITLE
Exporting the python code

### ISSUE THREAD

**Issue by melovv** [arunnbaba/pandas_ui#27]
Hello there!

This tool looks really great!

I was wondering how we can export the python code that created the dataset.
For instance, suppose I load a csv and apply a lot of cleaning and processing. I'd like to get not only the new dataframe but also the source code that created that dataframe.

Thanks a lot and keep doing you awesome work with this amazing tool!!!

**Comment by arunnbaba** [comment]
Hi melovv,

Thanks for the kind words, You can download your processed dataframe using the below commands
>>get_df() # to get the dataframe
>>get_meltdf() or get_pivotdf() # to get melt or pivot dataframes if any.

To get the code which was generated by the tool , you have to navigate to the History tab and you can get it there.
