### ISSUE TITLE
Dataframe not showing 

### ISSUE THREAD

**Issue by Chocoder** [arunnbaba/pandas_ui#28]
Hello, I can run the pandas_ui without any error BUT I cannot see the dataframe at the bottom of the visual...

All up functions work fine, but without df (qgrid I guess) it is not efficient at all...

Could you help?

**Comment by arunnbaba** [comment]
Hi,

Thanks for bringing this to the notification, This error will be mitigated from the next update release.

In the meantime you can manually correct this issue by downgrading ipywidgets please find the commands for that as follows.


pip uninstall ipywidgets

pip install ipywidgets==7.5.1

jupyter nbextension enable --py widgetsnbextension --sys-prefix

**Comment by Anvesh191990** [comment]
Hi Arun,

I found this very useful, but I don't see the dataframe under table view. Do you have any other alternatives?
