### ISSUE TITLE
Sep or delimiter option

### ISSUE THREAD

**Issue by ManuelBanza** [arunnbaba/pandas_ui#4]
Hi,

I saw that it can reads excel files separated by comma and put it in a dataframe, but I tried with a file that is separated by semi colon and it did not work. Is it possible to put some optional variable?

Cheers

**Comment by arunnbaba** [comment]
Well, using CSV files is kind of a standard way to give as a input for
dtaframe , u can change the delimiter before passing it to the function.
However in the future version will surely look into these issues and
support Excel files as well, thank you and please do share with your
connections.
