### ISSUE TITLE
Filter text / string attributes

### ISSUE THREAD

**Issue by ManuelBanza** [arunnbaba/pandas_ui#5]
Hi,

Is it possible to filter string values?

I get this error

![Captura de ecrã 2020-06-17, às 18 53 50](https://user-images.githubusercontent.com/53525022/84932387-1fb51700-b0cc-11ea-95e1-768ec01a9c8c.png)

**Comment by arunnbaba** [comment]
Yes, you can surely filter text, just try "has value" instead of "==".

**Comment by ManuelBanza** [comment]
Hi @arunnbaba 

I only have this options:

<img width="957" alt="Captura de ecrã 2020-06-17, às 22 55 22" src="https://user-images.githubusercontent.com/53525022/84954652-af1ef200-b0ed-11ea-9dc3-50b4cd61cc60.png">

**Comment by arunnbaba** [comment]
Hi,

You are correct "has values" is an option in update values not in filtering rows thanks for pointing it out.

But you can filter string values in "filter" itself. Please refer to the attached for further information.

Please let me know if I can help any further.
![filter1](https://user-images.githubusercontent.com/14852442/84975333-bae8d380-b142-11ea-879f-7ebb0b112273.PNG)
![filter2](https://user-images.githubusercontent.com/14852442/84975345-c6d49580-b142-11ea-8135-6cf95e32f96e.PNG)

**Comment by ManuelBanza** [comment]
Hi,

I tried again two times and one time I got the same error in the image above:

Exception raised with the option selected, Please go BACK 

The second time it worked however it filtered more that the option I filtered.

**Comment by arunnbaba** [comment]
Please post the file and the options ur selecting and thanks for your contributions in this repository. :)

**Comment by ManuelBanza** [comment]
You can find for example this dataset:
https://www.kaggle.com/jessemostipak/hotel-booking-demand

Try for example filtering the column country with value PRT. I tried now and it gave me the same error.
Thank you for doing an amazing library!

**Comment by arunnbaba** [comment]
I have tried the operation u have mentioned with the file you have given but am not getting any errors.

Please find the attached.

![filter01](https://user-images.githubusercontent.com/14852442/85012805-35384880-b181-11ea-84b0-f1a372dacaaf.PNG)

![filter02](https://user-images.githubusercontent.com/14852442/85012817-39fcfc80-b181-11ea-974b-011d3af5edfc.PNG)

**Comment by arunnbaba** [comment]
Please check whether u r environment is compatible with the tool. I hope it helps.

**Comment by ManuelBanza** [comment]
hi,

so if I use Google Chrome it works fine, but when I use Safari it doesn´t... But with Chrome everything is ok 👍

**Comment by arunnbaba** [comment]
Glad it helped
