### ISSUE TITLE
start wrangling from an existing DF or a CSV string (not only a file path)

### ISSUE THREAD

**Issue by costezki** [arunnbaba/pandas_ui#6]
Great library! 

It would be nice to be able to enable multiple starting points. Currently, it is possible to start from a CVS file only. Would be nice to visualise/wrangle an existing DF or create one from a CSV string.

**Comment by arunnbaba** [comment]
Hi, 

Thanks for your kind words, and Yes currently the tool accepts only the CSV files as input. will add these functionalities in the next beta release.
